name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    
    - name: Build and push Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} .
    
    - name: Run Tests
      run: docker run -e CI=true ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} npm test
    
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: docker-app
        environment_name: Docker-app-env
        existing_bucket_name: elasticbeanstalk-us-east-123456789012
        region: eu-north-1
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
